// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkpyvtragdluawzrlxbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcHl2dHJhZ2RsdWF3enJseGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTQ1NDIsImV4cCI6MjA2ODU3MDU0Mn0.o3EBf6PSTahDgVUGGQV8FonsZwlo3bZC8g4S6dMvyDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});